### ISSUE TITLE
Can't find variable: EMPTY

### ISSUE THREAD

**Issue by dgendill** [slamdata/purescript-avar#4]
I'm not sure if this issue should go into purescript-aff or this repo, but when I use purescript-aff#4.0.0 and use the `makeVar` function, the Control.Monad.Eff.AVar module is missing the EMPTY variable in the compiled JavaScript. I think these steps can reproduce the issue.  Here's a sample module...

```purescript
module Test.Main where

import Prelude

import Control.Monad.Aff (message, runAff_)
import Control.Monad.Aff.AVar (makeEmptyVar, makeVar)
import Control.Monad.Eff.Console (log)
import Control.Monad.Eff.Exception (stack)
import Data.Either (Either(..))

main = runAff_ (case _ of
    Left err -> do
      log $ "ERROR: " <> message err
      log $ show (stack err)
    Right r -> log "OK"
  ) $ do
    a <- makeVar "s"
    pure unit
```

If you compile using `pulp build --main Test.Main --to test.js`, the resulting `test.js` has this compiled `Control.Monad.Eff.AVar` module.

```javascript
(function(exports) {
  /* globals exports, setTimeout */
  /* jshint -W097 */
  "use strict";

  // ...

  function drainVar (util, avar) {

    // ...

    if (value === EMPTY && (p = takeHead(ps))) {
      avar.value = value = p.value;
    }
  }
  // ...
})(PS["Control.Monad.Eff.AVar"] = PS["Control.Monad.Eff.AVar"] || {});
```

However, if I substitute `makeEmptyVar` for `makeVar`, then I get this output...

```javascript
(function(exports) {
  /* globals exports, setTimeout */
  /* jshint -W097 */

  "use strict";

  var EMPTY = {};
  // ...
```

I'm using compile 0.11.6.

**Comment by coot** [comment]
I was hit by this too.  That's an issue with `purs bundle --main Test.Main --module Test.Main`.  The DCE performed removed the `EMPTY` variable.   (zephyr)[https://github.com/coot/zephry] does not suffer from this.

**Comment by natefaubion** [comment]
`purs bundle` is extremely brittle when it comes to DCE on FFI code 😞. It's designed to perform DCE on PureScript code which has very specific patterns, completely ignoring other common JS things (like `switch`es). I had tested the bundler with `Test.Main` and everything worked, so I assumed it was OK, but clearly there are bad cases where DCE will remove the var even though it's in use. I fixed this for `Aff` by putting everything important in a big IIFE, which `purs bundle` seems to leave alone.

**Comment by natefaubion** [comment]
Can you try out the changes in #6 and confirm it fixes your problem?

**Comment by coot** [comment]
The `EMPTY` is now preserved. With zephyr we'll stop having this kind of problems, since DCE in foreign modules can be done by javascript tooling, while DCE on corefn is much easier to do.

**Comment by dgendill** [comment]
#6 fixed it for me. Thanks, Nate!
