### ISSUE TITLE
Is not published on puresuit.

### ISSUE THREAD

**Issue by coot** [slamdata/purescript-avar#5]

**Comment by natefaubion** [comment]
Not sure why :/ The `.travis.yml` file has the stuff to do it automatically, but for some reason it's not succeeding.

**Comment by natefaubion** [comment]
https://travis-ci.org/slamdata/purescript-avar#L899 for some reason pulp thinks the working tree is dirty.

**Comment by natefaubion** [comment]
I've uploaded it manually for now.

**Comment by garyb** [comment]
This happens on a bunch (maybe all) of the travis auto-publishes now. It's really quite irritating.

**Comment by safareli** [comment]
This can be closed
