### ISSUE TITLE
Limiting size of internal queue

### ISSUE THREAD

**Issue by felixSchl** [slamdata/purescript-avar#7]
I am porting pipes-concurrency to purescript and am looking for a suitable way to implement the buffering of values.

I need to implement:

```purescript
data Buffer a
  = Unbounded   -- this is what AVar currently does
  | Bounded Int -- ?
  | Latest a    -- ?
  | Newest Int  -- ?
```

Do you think this project is the right candidate to implement `Newest Int` and `Bounded Int` on top of?

**Comment by natefaubion** [comment]
I think ideally these sorts of things would be built on top of `avar` as a separate library.

**Comment by natefaubion** [comment]
Or I should say, while avar does have an internal queue, it is not a general purpose queue, but it can be used to implement concurrent queues like what you want.

**Comment by jdegoes** [comment]
Agreed these should be built on top of `AVar` (and `TVar` when we have it). In Haskell, there are a number of queues built on top of `MVar` (which is their equivalent of `AVar`), so it should be straightforward to port.

**Comment by safareli** [comment]
I think this could be closed by as there is https://github.com/slamdata/purescript-concurrent-queues

**Comment by cryogenian** [comment]
Right
