### ISSUE TITLE
`takeVar` does not block

### ISSUE THREAD

**Issue by felixSchl** [slamdata/purescript-avar#8]
Hey, I am trying to understand how the avar semantics have changed from v3.
I expected this test to hang forever, but it just returns:

```purescript
main :: Eff _ Unit
main = run' (defaultConfig { timeout = Nothing }) [consoleReporter] do
  describe "avars" do
    it "should block" do
      x <- makeEmptyVar
      takeVar x
```

The same occurs also for:

```purescript
main :: Eff _ Unit
main = void $ launchAff do
  x <- makeEmptyVar
  takeVar x
```

Is that the intended behavior?

**Comment by natefaubion** [comment]
It deadlocks, but it can't actually block since it isn't synchronous. Deadlocking results in things being queued, but no one is around to unqueue them, which means the process will just exit since there's nothing left to do.

**Comment by felixSchl** [comment]
Thank you for explaining, that make perfect sense.
Would you also be able to explain to me why this leaks memory?

```purescript

main :: Eff _ Unit
main = void $ launchAff do
  var <- makeEmptyVar
  void $ forkAff do
    let loop n = do
          traceAnyA $ "sending: " <> show n
          putVar n var
          traceAnyA $ "after sending..."
          when (n < 10000000) $ loop (n + 1)
    loop 1

  forever do
    traceAnyA =<< takeVar var
```

**Comment by felixSchl** [comment]
For more context, I am working on a library [purescript-redux-saga](https://github.com/felixschl/purescript-redux-saga) but I am plagued with memory increasing over time. I hoped updating to aff v4 would alleviate this since consumers are being cancelled AFAICT. I would really, really appreciate your input on this. Essentially, I am trying to use avars as a channel mechanism where values trickle down into sub-sagas. The library is pretty small, if you wanted to take a look. I've been battling with this for quite a while now :/

**Comment by felixSchl** [comment]
Actually, breaking the execution context seems to alleviate the memory issue:

```purescript
main :: Eff _ Unit
main = void $ launchAff do
  var <- makeEmptyVar
  void $ forkAff do
    let loop n = do
          liftAff $ delay $ 0.0 # Milliseconds
          traceAnyA $ "sending: " <> show n
          putVar n var
          traceAnyA $ "after sending..."
          when (n < 10000000) $ loop (n + 1)
    loop 1

  forever do
    traceAnyA =<< takeVar var
```

**Comment by natefaubion** [comment]
@felixSchl I would expect your first example to be fine, but maybe there's an issue with the main `drainVar` loop which is not releasing something while the loop is running.

**Comment by natefaubion** [comment]
Also, is it actually leaking memory, or is the GC just choosing not to reclaim it? It can be hard to tell sometimes.

**Comment by felixSchl** [comment]
I am not sure. After sending a quarter of million things into the avar, I am using up 1.5gb of memory. I would've hoped the GC to kick in since I am not retaining any references anywhere in the program above.

**Comment by felixSchl** [comment]
I will close this for now as breaking the execution context seems good enough for me and the memory issue is unrelated to the title of this issue.

**Comment by natefaubion** [comment]
I would also be interested to see if it's an issue with Aff rather than AVar. We should test the same thing with the Eff interface.
